### ISSUE TITLE
MAP count_name: compiler bug

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#105]
The following statement compiles:
S = MAP(mirna_genes AS BAG(mirna_id); count_name: gene_count; ) CNV MIRNA_GENE;
but the following not:
S = MAP(count_name: gene_count; mirna_genes AS BAG(mirna_id)) CNV MIRNA_GENE;
returning error: Missing ";" character at the end of the query

Probably a small compiler bug to be fixed.

You can use the following query for testing:
CNV = SELECT(manually_curated__dataType == 'cnv' AND manually_curated__tumor_tag == 'luad') HG19_TCGA_cnv;
MIRNA_GENE = SELECT(manually_curated__dataType == 'mirnaseq' AND manually_curated__tumor_tag == 'luad') HG19_TCGA_mirnaseq_mirna;
CNV_GENE_0 = MAP(mirna_genes AS BAG(mirna_id); joinby: biospecimen_sample__bcr_sample_barcode) CNV MIRNA_GENE;
MATERIALIZE CNV_GENE_0 INTO CNV_GENE_0;

**Comment by pp86** [comment]
@marcomass , the former does not compile because you are passing a named parameter (count_name), before the unnamed parameter (list of aggregates).

For any operator the order of the parameters is:
1 - first the unnamed parameter (if any)
2 - all the named parameter, in any order

This should be described specified in the documentation (if I recall correctly it is written somewhere, but I may be wrong). @sunbrn 


For the error message, I will point to the related issue: #106
