### ISSUE TITLE
Compile error in GMQL-Python

### ISSUE THREAD

**Issue by acanakoglu** [DEIB-GECO/GMQL#41]
please check before commit.

**Comment by lucananni93** [comment]
What kind of error? Can you post the text of the exception?

**Comment by acanakoglu** [comment]
Please check the attached file.

[mvn_compile.txt](https://github.com/DEIB-GECO/GMQL/files/1053183/mvn_compile.txt)

**Comment by lucananni93** [comment]
This is due to the modification done to the PROJECT operator for including the ALLBUT construct.
I didn't upload my code after this modification. My commit was working at the time. Now of course it contains an "error" (in the sense that it is no more compatible with the new GMQLServer.PROJECT).
ASAP I will upload my fix. 
It is strange the fact that when the ALLBUT modification was committed this error went undiscovered...

**Comment by akaitoua** [comment]
@lucananni93 did you solve this?
