### ISSUE TITLE
COVER(ALL,ANY)

### ISSUE THREAD

**Issue by eirinistam** [DEIB-GECO/GMQL#83]
Hi @akaitoua this is for u,
When I run the following query I receive the error: empty input, but the dataset(I enclose all in the zip) contains everything(.gtf, metadata, schema) and must return also a none empty dataset.
DATA_SET_VAR = SELECT() dataset_2;
D= COVER(ALL, ANY) DATA_SET_VAR;
MATERIALIZE D INTO DATA;
[bug report.zip](https://github.com/DEIB-GECO/GMQL/files/1434645/bug.report.zip)

**Comment by akaitoua** [comment]
@eirinistam,

Your query will give empty dataset because Your down limit for the cover operation is ALL (which is in this case 6 samples) and by looking to your data i did not see any accumulation of the data that is greater than 4. 
Please **double check** your data before writing a bug in the bug list.

**Comment by eirinistam** [comment]
The final result has to be empty not the first select( this I mean has to retutn a non empty input to cover)  and also gives the error instead of an empty dataset final result.

**Comment by akaitoua** [comment]
@andreagulino, I think the error in creating empty dataset comes from the profiler.

**Comment by andreagulino** [comment]
was already fixed
