### ISSUE TITLE
JOIN( UPSTREAM) wrong output regions and score

### ISSUE THREAD

**Issue by eirinistam** [DEIB-GECO/GMQL#92]
With the following query:
D1 = SELECT(region: chr == chr4) example_dataset_1;
D2 = SELECT(region: chr == chr4) example_dataset_2;
RES = JOIN(MD(1), UP; output: RIGHT) D1 D2;
MATERIALIZE RES INTO join_11;
Received wrong regions ouput and scores
[join_11.zip](https://github.com/DEIB-GECO/GMQL/files/1518360/join_11.zip)
![picture1](https://user-images.githubusercontent.com/26028864/33479690-4b0efe40-d68e-11e7-8050-a4bf88f38830.png)

**Comment by marcomass** [comment]
Related to issue #86 
Please Eirini, can you upload also the screen shot?

**Comment by pp86** [comment]
@marcomass @eirinistam 

0 as score is correct, since the score field of the result is set to 0.0 by the GTF converter.
chr4	GMQL	Region	180	240	**0.0**	-	.	D1.source "GMQL"; D1.feature "Region"; **D1.score "0.9"**; D1.frame "."; D1.name "."; D1.signal "15"; D1.pvalue "15.1452"; D1.qvalue "-1"; D1.peak "-1"; D2.source "GMQL"; D2.feature "Region"; **D2.score "240"**; D2.frame "."; D2.name "."; D2.signal "17"; D2.pvalue "11.1675"; D2.qvalue "-1"; D2.peak "-1";

Is the problem with the first green region?Which should not be in the output?

**Comment by marcomass** [comment]
@pp86 
The predicate must be applied only upstream of the anchor region.
Only one copy of the green region on the right should be in the output (it is adjacent to the second blue region).
Here the definition:
●	in the positive strand (or when the strand is unknown), UP is true for those regions of the experiment whose right-end is lower than, or equal to, the left-end of the anchor, and DOWN is true for those regions of the experiment whose left-end is higher than, or equal to, the right-end of the anchor;
●	in the negative strand inequalities are exchanged;
●	remaining regions of the experiment must be overlapping with the anchor region.
